[2025-03-03T23:10:34.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T23:10:34.671+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict.train manual__2025-03-03T22:49:05.766617+00:00 [queued]>
[2025-03-03T23:10:34.690+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict.train manual__2025-03-03T22:49:05.766617+00:00 [queued]>
[2025-03-03T23:10:34.692+0000] {taskinstance.py:2865} INFO - Starting attempt 7 of 7
[2025-03-03T23:10:34.721+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2025-03-03 22:49:05.766617+00:00
[2025-03-03T23:10:34.738+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_predict', 'train', 'manual__2025-03-03T22:49:05.766617+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/train_predict.py', '--cfg-path', '/tmp/tmp4g7tppmj']
[2025-03-03T23:10:34.740+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7286) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-03T23:10:34.742+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask train
[2025-03-03T23:10:34.742+0000] {standard_task_runner.py:72} INFO - Started process 7289 to run task
[2025-03-03T23:10:34.834+0000] {task_command.py:467} INFO - Running <TaskInstance: train_predict.train manual__2025-03-03T22:49:05.766617+00:00 [running]> on host b756940c1467
[2025-03-03T23:10:35.061+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_predict' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T22:49:05.766617+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T22:49:05.766617+00:00'
[2025-03-03T23:10:35.065+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-03T23:10:35.071+0000] {logging_mixin.py:190} INFO - 1
[2025-03-03T23:10:35.072+0000] {logging_mixin.py:190} INFO - 2
[2025-03-03T23:10:35.074+0000] {logging_mixin.py:190} INFO - 3
[2025-03-03T23:10:35.809+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-03T23:10:35.811+0000] {logging_mixin.py:190} INFO - 4
[2025-03-03T23:10:36.173+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-03T23:10:36.175+0000] {logging_mixin.py:190} INFO - Shivam ('View STOCK_DATA_VIEW successfully created.',)
[2025-03-03T23:12:00.635+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-03-03T23:12:00.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-03T23:12:00.644+0000] {process_utils.py:132} INFO - Sending 15 to group 7289. PIDs of all processes in the group: [7289]
[2025-03-03T23:12:00.645+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 7289
[2025-03-03T23:12:00.646+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-03T23:12:00.669+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_predict.py", line 86, in train
    cursor.execute(create_model_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 984, in execute
    ret = self._execute_helper(query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 695, in _execute_helper
    ret = self._connection.cmd_query(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1350, in cmd_query
    ret = self.rest.request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 491, in request
    return self._post_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 788, in _post_request
    ret = self._get_request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 690, in _get_request
    ret = self.fetch(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 854, in fetch
    ret = self._request_exec_wrapper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 896, in _request_exec_wrapper
    return_object = self._request_exec(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 1059, in _request_exec
    raw_ret = session.request(
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 330, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 145, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 106, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 104, in do_poll
    return poll_obj.poll(t)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-03T23:12:00.707+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=train_predict, task_id=train, run_id=manual__2025-03-03T22:49:05.766617+00:00, execution_date=20250303T224905, start_date=20250303T231034, end_date=20250303T231200
[2025-03-03T23:12:00.735+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-03T23:12:00.780+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=7289, status='terminated', exitcode=2, started='23:10:34') (7289) terminated with exit code 2
